server:
  port: 9081

spring:
  application:
    name: security
  datasource:
    url: jdbc:postgresql://localhost:5432/coupons
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    locations: classpath:db/migration
  security:
    user:
      name: admin
      password: password
      roles: manager
